import { onValue, push, ref, set } from 'firebase/database';
import React, { useRef, useState } from 'react';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useParams } from 'react-router-dom';
import { database } from '../../../utils/firebase';

import './chat.css';

const Chat = () => {
  const { roomId } = useParams();
  const { username, teamId } = useSelector((state) => state.player);
  const { team1Id } = useSelector((state) => state.teamOne);
  const { team2Id } = useSelector((state) => state.teamTwo);

  const bottomOfMessagesRef = useRef(null);
  const [msg, setMsg] = useState(''); // this is the currently inputted message by the user
  const [messages, setMessages] = useState({}); // these are all the messages in the chat
  /* chatroom is an array like this: 
    [
      { sender: 'topher', msg: 'hello world!'}, 
      { sender: 'rose', msg: 'this chatroom is so cool'}, 
      { sender: 'topher', msg: 'agreed.'}, 
    ]
  */

  const chatRef = ref(database, `rooms/${roomId}/chat`);

  useEffect(() => {
    onValue(chatRef, (snapshot) => {
      if (snapshot.exists()) {
        const snapshotValue = snapshot.val();
        setMessages(snapshotValue);
      } else {
        // did not find a chatRef
      }
    });
  }, []);

  useEffect(() => {
    bottomOfMessagesRef.current.scroll({ top: bottomOfMessagesRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages]);

  const handleMsgChange = (e) => setMsg(e.target.value);

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      const messageObjectForFirebase = {
        sender: username,
        msg: msg,
        teamId: teamId,
      };
      // put this message as a child of our message ref
      // The unique key generated by push() is based on a timestamp,
      // so list items are automatically ordered chronologically.
      const newMessageRef = push(chatRef);
      set(newMessageRef, messageObjectForFirebase);
      // chatRoom.push({ sender: username, msg});
      setMsg(''); // reset message input state to empty string

      // scrolldown to ref automatically!
      bottomOfMessagesRef.current.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
        inline: 'start',
      });
    }
  };

  return (
    <div className="chat-container">
      <div className="chat">
        <div className="messages" ref={bottomOfMessagesRef}>
          {Object.keys(messages).map((message) => {
            if (messages[message]['teamId'] === team1Id)
              return (
                <div key={message} className="team-one-message">
                  <span className="sender">{messages[message]['sender']}: </span>
                  {messages[message]['msg']}
                </div>
              );
            else if (messages[message]['teamId'] === team2Id)
              return (
                <div key={message} className="team-two-message">
                  <span className="sender">{messages[message]['sender']}: </span>
                  {messages[message]['msg']}
                </div>
              );
            else
              return (
                <div key={message} className="spectator-message">
                  <span className="sender">{messages[message]['sender']}: </span>
                  {messages[message]['msg']}
                </div>
              );
          })}
        </div>
      </div>
      <div className="input-container">
        <input
          placeholder="Type message & press enter"
          onChange={handleMsgChange}
          onKeyDown={handleKeyDown}
          value={msg}
        />
      </div>
    </div>
  );
};

export default Chat;
