import { onValue, push, ref, set } from 'firebase/database';
import React, { useRef, useState } from 'react';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useParams } from 'react-router-dom';
import { database } from '../../../utils/firebase';
import { RootState } from '../../../store/index.js';
import './chat.css';

// This is how the messages object looks in firebase - it is a string key and the value is a MsgType.
/* {
  -NNw7f9cwKyPmhH0Qu7h: {msg: 'from spectator', username: 'ben'}
  -NNw8ewwRkrKmDjon24H: {msg: 'message!', teamId: 14, username: 'rose'}
  } */
interface FirebaseMessageType {
  [key: string]: MsgType;
}
interface MsgType {
  username: string;
  msg: string;
  teamId: null | number;
}

const Chat = () => {
  const divRef = useRef<null | HTMLDivElement>(null);
  const { roomId } = useParams();
  const { username, teamId } = useSelector((state: RootState) => state.player);
  const { team1Id } = useSelector((state: RootState) => state.teamOne);
  const { team2Id } = useSelector((state: RootState) => state.teamTwo);
  const [msg, setMsg] = useState(''); // this is the currently inputted message by the user
  const [messages, setMessages] = useState<FirebaseMessageType>({}); // these are all the messages in the chat
  const chatRef = ref(database, `rooms/${roomId}/chat`); // firebase reference to all messages in room

  useEffect(() => {
    onValue(chatRef, (snapshot) => {
      if (snapshot.exists()) {
        const snapshotValue = snapshot.val();
        setMessages(snapshotValue);
      } else {
        // did not find a chatRef
      }
    });
  }, []);

  useEffect(() => {
    if (divRef.current)
      divRef.current.scroll({
        top: divRef.current.scrollHeight,
        behavior: 'smooth',
      });
  }, [messages]);

  const handleMsgChange = (e: React.ChangeEvent<HTMLInputElement>) => setMsg(e.target.value);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    const isMsgOnlyWhiteSpace = '' === msg.trim(); // don't let them send blank messages
    if (e.key === 'Enter' && !isMsgOnlyWhiteSpace) {
      const messageObjectForFirebase = { username, msg, teamId };
      // The unique key generated by push() is based on a timestamp,
      // so list items are automatically ordered chronologically.
      const newMessageRef = push(chatRef);
      set(newMessageRef, messageObjectForFirebase); // give newMessageRef the content
      setMsg(''); // reset message input state to empty string
    }
  };

  return (
    <div className="chat-container">
      <h3 className="chat-header">Chatroom</h3>
      <div className="chat">
        <div className="messages" ref={divRef}>
          {Object.keys(messages).map((message) => {
            if (messages[message]['teamId'] === team1Id)
              return (
                <div key={message} className="team-one-message">
                  <span className="sender">{messages[message]['username']}: </span>
                  {messages[message]['msg']}
                </div>
              );
            else if (messages[message]['teamId'] === team2Id)
              return (
                <div key={message} className="team-two-message">
                  <span className="sender">{messages[message]['username']}: </span>
                  {messages[message]['msg']}
                </div>
              );
            else
              return (
                <div key={message} className="spectator-message">
                  <span className="sender">{messages[message]['username']}: </span>
                  {messages[message]['msg']}
                </div>
              );
          })}
        </div>
      </div>
      <input
        className="message-input"
        placeholder="Type message & press enter"
        onChange={handleMsgChange}
        onKeyDown={handleKeyDown}
        value={msg}
      />
    </div>
  );
};

export default Chat;
